(define (problem planificacion-contenidos-base)
  (:domain planificacion-contenidos)

	(:objects 
    contenido1 contenido2 contenido3 contenido4 contenido5 contenido6 contenido7 contenido8 contenido9 - contenido
    dia1 dia2 dia3 dia4 dia5 dia6 dia7 dia8 dia9 dia10 dia11 dia12 dia13 dia14 dia15 dia16 dia17 dia18 dia19 dia20 dia21 dia22 dia23 dia24 dia25 dia26 dia27 dia28 dia29 dia30 dia31 - dia
  )

  (:init
    (predecesor contenido4 contenido3)
    (predecesor contenido5 contenido4)

    (quiere_ver contenido4)
    (quiere_ver contenido7)
    (quiere_ver contenido8)
    (quiere_ver contenido9)
    (quiere_ver contenido6)
    (quiere_ver contenido5)

    (= (numero_dia dia1) 1)
    (= (numero_dia dia2) 2)
    (= (numero_dia dia3) 3)
    (= (numero_dia dia4) 4)
    (= (numero_dia dia5) 5)
    (= (numero_dia dia6) 6)
    (= (numero_dia dia7) 7)
    (= (numero_dia dia8) 8)
    (= (numero_dia dia9) 9)
    (= (numero_dia dia10) 10)
    (= (numero_dia dia11) 11)
    (= (numero_dia dia12) 12)
    (= (numero_dia dia13) 13)
    (= (numero_dia dia14) 14)
    (= (numero_dia dia15) 15)
    (= (numero_dia dia16) 16)
    (= (numero_dia dia17) 17)
    (= (numero_dia dia18) 18)
    (= (numero_dia dia19) 19)
    (= (numero_dia dia20) 20)
    (= (numero_dia dia21) 21)
    (= (numero_dia dia22) 22)
    (= (numero_dia dia23) 23)
    (= (numero_dia dia24) 24)
    (= (numero_dia dia25) 25)
    (= (numero_dia dia26) 26)
    (= (numero_dia dia27) 27)
    (= (numero_dia dia28) 28)
    (= (numero_dia dia29) 29)
    (= (numero_dia dia30) 30)
    (= (numero_dia dia31) 31)

    (= (planificado_para contenido1) 0)
    (= (planificado_para contenido2) 0)
    (= (planificado_para contenido3) 0)
    (= (planificado_para contenido4) 0)
    (= (planificado_para contenido5) 0)
    (= (planificado_para contenido6) 0)
    (= (planificado_para contenido7) 0)
    (= (planificado_para contenido8) 0)
    (= (planificado_para contenido9) 0)

  )

  (:goal (forall (?c - contenido) (or (not (quiere_ver ?c)) (visto ?c))))
)