(define (problem planificacion-contenidos-ext4)
  (:domain planificacion-contenidos)

	(:objects 
    contenido1 contenido2 contenido3 contenido4 contenido5 contenido6 contenido7 contenido8 contenido9 contenido10 contenido11 contenido12 contenido13 - contenido
    dia1 dia2 dia3 dia4 dia5 dia6 dia7 dia8 dia9 dia10 dia11 dia12 dia13 dia14 dia15 dia16 dia17 dia18 dia19 dia20 dia21 dia22 dia23 dia24 dia25 dia26 dia27 dia28 dia29 dia30 dia31 - dia
  )

  (:init
    (= (duracion contenido1) 15)
    (= (duracion contenido2) 60)
    (= (duracion contenido3) 75)
    (= (duracion contenido4) 30)
    (= (duracion contenido5) 60)
    (= (duracion contenido6) 75)
    (= (duracion contenido7) 15)
    (= (duracion contenido8) 75)
    (= (duracion contenido9) 75)
    (= (duracion contenido10) 60)
    (= (duracion contenido11) 60)
    (= (duracion contenido12) 75)
    (= (duracion contenido13) 75)

    (= (minutos_consumidos dia1) 0)
    (= (minutos_consumidos dia2) 0)
    (= (minutos_consumidos dia3) 0)
    (= (minutos_consumidos dia4) 0)
    (= (minutos_consumidos dia5) 0)
    (= (minutos_consumidos dia6) 0)
    (= (minutos_consumidos dia7) 0)
    (= (minutos_consumidos dia8) 0)
    (= (minutos_consumidos dia9) 0)
    (= (minutos_consumidos dia10) 0)
    (= (minutos_consumidos dia11) 0)
    (= (minutos_consumidos dia12) 0)
    (= (minutos_consumidos dia13) 0)
    (= (minutos_consumidos dia14) 0)
    (= (minutos_consumidos dia15) 0)
    (= (minutos_consumidos dia16) 0)
    (= (minutos_consumidos dia17) 0)
    (= (minutos_consumidos dia18) 0)
    (= (minutos_consumidos dia19) 0)
    (= (minutos_consumidos dia20) 0)
    (= (minutos_consumidos dia21) 0)
    (= (minutos_consumidos dia22) 0)
    (= (minutos_consumidos dia23) 0)
    (= (minutos_consumidos dia24) 0)
    (= (minutos_consumidos dia25) 0)
    (= (minutos_consumidos dia26) 0)
    (= (minutos_consumidos dia27) 0)
    (= (minutos_consumidos dia28) 0)
    (= (minutos_consumidos dia29) 0)
    (= (minutos_consumidos dia30) 0)
    (= (minutos_consumidos dia31) 0)

    (predecesor contenido12 contenido11)
    (predecesor contenido4 contenido3)
    (predecesor contenido5 contenido4)
    (predecesor contenido10 contenido9)
    (predecesor contenido7 contenido6)
    (predecesor contenido13 contenido12)
    (predecesor contenido6 contenido5)

    (paralelo contenido6 contenido12)
    (paralelo contenido2 contenido9)
    (paralelo contenido1 contenido12)
    (paralelo contenido5 contenido12)
    (paralelo contenido7 contenido9)

    (quiere_ver contenido12)
    (quiere_ver contenido11)
    (quiere_ver contenido9)
    (quiere_ver contenido13)
    (quiere_ver contenido3)
    (quiere_ver contenido8)
    (quiere_ver contenido5)

    (= (numero_dia dia1) 1)
    (= (numero_dia dia2) 2)
    (= (numero_dia dia3) 3)
    (= (numero_dia dia4) 4)
    (= (numero_dia dia5) 5)
    (= (numero_dia dia6) 6)
    (= (numero_dia dia7) 7)
    (= (numero_dia dia8) 8)
    (= (numero_dia dia9) 9)
    (= (numero_dia dia10) 10)
    (= (numero_dia dia11) 11)
    (= (numero_dia dia12) 12)
    (= (numero_dia dia13) 13)
    (= (numero_dia dia14) 14)
    (= (numero_dia dia15) 15)
    (= (numero_dia dia16) 16)
    (= (numero_dia dia17) 17)
    (= (numero_dia dia18) 18)
    (= (numero_dia dia19) 19)
    (= (numero_dia dia20) 20)
    (= (numero_dia dia21) 21)
    (= (numero_dia dia22) 22)
    (= (numero_dia dia23) 23)
    (= (numero_dia dia24) 24)
    (= (numero_dia dia25) 25)
    (= (numero_dia dia26) 26)
    (= (numero_dia dia27) 27)
    (= (numero_dia dia28) 28)
    (= (numero_dia dia29) 29)
    (= (numero_dia dia30) 30)
    (= (numero_dia dia31) 31)

    (= (planificado_para contenido1) 0)
    (= (planificado_para contenido2) 0)
    (= (planificado_para contenido3) 0)
    (= (planificado_para contenido4) 0)
    (= (planificado_para contenido5) 0)
    (= (planificado_para contenido6) 0)
    (= (planificado_para contenido7) 0)
    (= (planificado_para contenido8) 0)
    (= (planificado_para contenido9) 0)
    (= (planificado_para contenido10) 0)
    (= (planificado_para contenido11) 0)
    (= (planificado_para contenido12) 0)
    (= (planificado_para contenido13) 0)
  )

  (:goal (forall (?c - contenido) (or (not (quiere_ver ?c)) (visto ?c))))
)